apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-documentation-test
  description: Este repositorio está sincronizado con Backstage.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: mframirezfuentes/backstage-test
spec:
  type: library
  owner: mframirezfuentes@gmail.com
  lifecycle: production
plugins:
  - techdocs-core